server.port=0

spring.application.name=order-service
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=dbuser
spring.datasource.password=12345

spring.cloud.openfeign.client.config.default.connectTimeout=1000
spring.cloud.openfeign.client.config.default.readTimeout=2000
spring.cloud.openfeign.client.config.product-service.connectTimeout=1000
spring.cloud.openfeign.client.config.product-service.readTimeout=2000
spring.cloud.openfeign.client.config.inventory-service.connectTimeout=1000
spring.cloud.openfeign.client.config.inventory-service.readTimeout=2000
spring.cloud.openfeign.circuitbreaker.enabled=true

resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=5
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=10s
resilience4j.circuitbreaker.configs.default.ignoreExceptions[0]=feign.FeignException$BadRequest
resilience4j.circuitbreaker.configs.default.ignoreExceptions[1]=feign.FeignException$NotFound
resilience4j.circuitbreaker.configs.default.ignoreExceptions[2]=feign.FeignException$Conflict

resilience4j.timelimiter.configs.default.timeoutDuration=4s
