logging.level.org.springframework.web=DEBUG
spring.mvc.log-request-details=true

logging.level.ru.yandex.practicum.order.client=DEBUG
spring.cloud.openfeign.client.config.default.loggerLevel=full
spring.cloud.openfeign.client.config.product-service.loggerLevel=full
spring.cloud.openfeign.client.config.inventory-service.loggerLevel=full
