logging.level.org.springframework.web=DEBUG
logging.level.org.zalando.logbook=DEBUG
logging.level.shm.telemetry.aggregator=DEBUG

spring.application.name=smart-home-tech-aggregator
spring.main.web-application-type=none

kafka.server=localhost:9092
kafka.producer.topic=telemetry.snapshots.v1
kafka.consumer.topic=telemetry.sensors.v1
kafka.consumer.client-id=aggregator-sensor-event-consumer-1
kafka.consumer.group-id=aggregator.sensor-event-consumers
kafka.consumer.consume-attempt-timeout-ms=1000
