server.port=8081

spring.application.name=analyzer
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/telemetry_analyzer
spring.datasource.username=dbuser
spring.datasource.password=12345

kafka.server=localhost:9092
kafka.consumer.snapshot-processor.topic=telemetry.snapshots.v1
kafka.consumer.snapshot-processor.client-id=snapshot-processor-1
kafka.consumer.snapshot-processor.group-id=snapshot-processor
kafka.consumer.hub-event-processor.topic=telemetry.hubs.v1
kafka.consumer.hub-event-processor.client-id=hub-event-processor-1
kafka.consumer.hub-event-processor.group-id=hub-event-processor
kafka.consumer.poll-timeout=1000

logging.level.shm.telemetry.analyzer=DEBUG