logging.level.org.springframework.web=DEBUG
logging.level.org.zalando.logbook=DEBUG
spring.application.name=smart-home-tech-collector
server.port=8080

kafka.server=localhost:9092
kafka.topic.sensor-events=telemetry.sensors.v1
kafka.topic.hub-events=telemetry.hubs.v1

grpc.server.port=59091